### ISSUE TITLE
Scd4x forced calibration code not working properly

### ISSUE THREAD

**Issue by rvadrichem** [Sensirion/arduino-snippets#5]
Hi,
I found that your code "SCD4x_I2C_FRC_Forced_Recalibration_Example.ino" was not working properly.
Instead of waiting for the sensor to startup and equalize itself to ambient levels, it started the calibration directly after powerup.

I found that at line 99, the delay was  commented. 

97  // wait for another 5 minutes to equilibrate sensor to ambient
98  Serial.println("# Waiting 5 minutes for equilibration");
99  //delay(5 * 60 * 1000);

I uncommented this delay, but also moved it up to line 60. This was because the values used as "CO2 values before recalibration" (lines 66-76) where saved before the initial equilibration delay at line 99.

Could you confirm this?
After I made the changes, sensorreadings where as expected from ~400PPM co2 levels in the outside ambient air.

**Comment by LeonieFierz** [comment]
Hi,
thank you for contacting us.
You are right, in order to have a reasonable calibration you have to uncomment the delay of 5minutes on line 99.
It makes sense to measure and show the values "before calibration" after the delay, but it has no influence on the calibration as the values are actually not used. The ppm concentration used as calibration value (value from external reference) is set on line 112.
We will see how we can clarify the example.
Best, Léonie

**Comment by rvadrichem** [comment]
Thank you for the quick response and clarifying!
